### ISSUE TITLE
`getModel` has changed to `getAssignment` in SBV

### ISSUE THREAD

**Issue by jmct** [dorchard/gram-lang#6]
SBV has changed under your feet! See: [See here](https://github.com/LeventErkok/sbv/commit/dba4cb2d3c930f1cbef1434118998db35ff11340)

There's two obvious ways to fix this: update gram_lang to a newer SBV, or put an upper bound on the version of SBV in the cabal file.

If you want to go with the former, let me know and I'll be happy to make the patch.

It's also possible that I've misunderstood something, in which case please ignore this :)

**Comment by vimuel** [comment]
Thank you for opening an issue on this.

I made a [new branch](https://github.com/dorchard/gram_lang/tree/new-sbv) where we depend on sbv-7.3. Could you try `stack install`ing that and get back to me?

**Comment by vimuel** [comment]
We are now using sbv-7.3 in master.
